//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18033
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextSummarizationLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextSummarizationLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;dictionary lang=&quot;English&quot; maintainer=&quot;nadav256@hotmail.com&quot;&gt;
        ///  &lt;stemmer&gt;
        ///
        ///
        ///    &lt;step1_pre&gt;
        ///      &lt;rule&gt;&quot;|&lt;/rule&gt;
        ///      &lt;rule&gt;(|&lt;/rule&gt;
        ///      &lt;rule&gt;&apos;|&lt;/rule&gt;
        ///    &lt;/step1_pre&gt;
        ///
        ///
        ///    &lt;step1_post&gt;
        ///      &lt;rule&gt;.&quot;|&lt;/rule&gt;
        ///      &lt;rule&gt;,&quot;|&lt;/rule&gt;
        ///      &lt;rule&gt;,&apos;|&lt;/rule&gt;
        ///      &lt;rule&gt;.|&lt;/rule&gt;
        ///      &lt;rule&gt;..|&lt;/rule&gt;
        ///      &lt;rule&gt;...|&lt;/rule&gt;
        ///      &lt;rule&gt;,|&lt;/rule&gt;
        ///      &lt;rule&gt;&quot;|&lt;/rule&gt;
        ///      &lt;rule&gt;&quot;)|&lt;/rule&gt;
        ///      &lt;rule&gt;)|&lt;/rule&gt;
        ///      &lt;rule&gt;?|&lt;/rule&gt;
        ///      &lt;rule&gt;:|&lt;/rule&gt; [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;dictionary lang=&quot;russian&quot;&gt;
        ///  &lt;stemmer&gt;
        ///
        ///    &lt;step1_pre&gt;
        ///      &lt;rule&gt;&quot;|&lt;/rule&gt;
        ///      &lt;rule&gt;(|&lt;/rule&gt;
        ///    &lt;/step1_pre&gt;
        ///
        ///
        ///    &lt;step1_post&gt;
        ///      &lt;rule&gt;.&quot;|&lt;/rule&gt;
        ///      &lt;rule&gt;,&quot;|&lt;/rule&gt;
        ///      &lt;rule&gt;.|&lt;/rule&gt;
        ///      &lt;rule&gt;,|&lt;/rule&gt;
        ///      &lt;rule&gt;&quot;|&lt;/rule&gt;
        ///      &lt;rule&gt;)|&lt;/rule&gt;
        ///      &lt;rule&gt;?|&lt;/rule&gt;
        ///      &lt;rule&gt;:|&lt;/rule&gt;
        ///      &lt;rule&gt;;|&lt;/rule&gt;
        ///      &lt;rule&gt;!|&lt;/rule&gt;
        ///    &lt;/step1_post&gt;
        ///
        ///
        ///    &lt;manual&gt;
        ///      &lt;rule&gt;wrote|write&lt;/rule&gt;
        ///      &lt;rule&gt;came|come&lt;/rule&gt;
        ///      &lt;ru [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
    }
}
